#!/usr/bin/env bash
# Bash Strict Mode: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'
# Bash Strict Mode

dotfiles::symlink_files ~/.dotfiles/shells/inputrc ~/.inputrc
dotfiles::symlink_files ~/.dotfiles/shells/bashrc ~/.bashrc
dotfiles::symlink_files ~/.dotfiles/shells/profile ~/.profile

