#!/usr/bin/env bash
# Bash Strict Mode: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'
# Bash Strict Mode

# setup .zsh
dotfiles::symlink_files ~/.dotfiles/claude ~/.claude

