#!/usr/bin/env bash
# Bash Strict Mode: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'
# Bash Strict Mode

dotfiles::symlink_files ~/.dotfiles/git/config ~/.gitconfig
dotfiles::symlink_files ~/.dotfiles/git/ignore ~/.gitignore

if [[ ! -f ~/.local/git/config ]] ; then
    echo_yellow '-[ ] GIT: add user and email to ~/.config/git/config'
    mkdir ~/.local/git &> /dev/null || true
    cat <<EOF > ~/.local/git/config
[user]
    name = 
    email = 
EOF
fi

