#!/usr/bin/env bash
# Bash Strict Mode: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'
# Bash Strict Mode

# TODO: take a parameter to limit the number of packages to install. This is useful for debugging.
# TODO: take a flag called --debug to print out logs of what is happening.

# ref: http://stackoverflow.com/a/246128/4301584
DOTFILES_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"

source "$DOTFILES_ROOT/shells/bash_utils.sh"
source "$DOTFILES_ROOT/shells/env.sh"

# Symlink the current folder to .dotfiles
dotfiles::symlink_files $DOTFILES_ROOT $HOME/.dotfiles;
cd $HOME/.dotfiles
log "dotfiles root $DOTFILES_ROOT"

# Starting the fun stuff
# ----------------------

# Ask for the administrator password upfront
if command_exists sudo; then
    sudo -v
    # Keep-alive: update existing `sudo` time stamp until `.macos` has finished
    while true; do
        sudo -n true;
        sleep 60;
        kill -0 "$$" || exit;
    done 2>/dev/null &
fi

# Make sure expected folders exist
mkdir $HOME/.local &> /dev/null || true
mkdir $HOME/.local/bin &> /dev/null || true

# Install Scripts
# Run install scripts for each folder in dotfiles/
for dir in */ ; do
    log Installing the $dir directory:
    cd $dir;
    echo "Installing $dir"

    if [ -f install ]; then
        source ./install
    fi

    log Finished $dir directory:
    cd $HOME/.dotfiles
done

echo_green "done"
