#!/bin/sh
# Compile ./keybindings into the generated rule block in macOS/karabiner.json.
#
# These hotkeys used to live in skhd, which reads keys through a CGEventTap.
# macOS starves every event tap while any app holds Secure Keyboard Entry, and
# Slack leaks it whenever a password field loses focus in an unusual way, so
# the hotkeys died silently with nothing in any log. Karabiner reads from a
# virtual HID device below the window server, which secure input does not
# affect.
#
# Run after editing ./keybindings, then commit both files.
# --check reports whether the committed JSON is stale and changes nothing.
set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
bindings=$here/keybindings
config=$here/../karabiner.json
description='yabai hotkeys (generated by macOS/yabai/gen-karabiner-rules.sh; do not edit)'

# shell_command runs under a bare /bin/sh, not a login shell, so Homebrew is
# not on PATH. cycle-window.sh hardcodes its own paths; this covers the rest.
path_prefix='export PATH=/opt/homebrew/bin:$PATH; '

tab=$(printf '\t')

manipulators=$(
  awk '
    { sub(/#.*/, "") }
    /^[[:space:]]*$/ { next }
    {
      colon = index($0, ":")
      lhs = substr($0, 1, colon - 1)
      cmd = substr($0, colon + 1)
      dash = index(lhs, "-")
      mods = substr(lhs, 1, dash - 1)
      key  = substr(lhs, dash + 1)
      gsub(/[[:space:]]/, "", mods)
      gsub(/[[:space:]]/, "", key)
      sub(/^[[:space:]]+/, "", cmd)
      sub(/[[:space:]]+$/, "", cmd)
      print mods "\t" key "\t" cmd
    }
  ' "$bindings" \
  | while IFS="$tab" read -r mods key cmd; do
      jq -n --arg key "$key" --arg mods "$mods" --arg cmd "$path_prefix$cmd" '
        {
          type: "basic",
          from: {
            key_code: $key,
            modifiers: {
              mandatory: ($mods | split("+")
                | map({ctrl: "control", cmd: "command", alt: "option", opt: "option"}[.] // .))
            }
          },
          to: [{ shell_command: $cmd }]
        }'
    done \
  | jq -s .
)

rule=$(jq -n --arg description "$description" --argjson manipulators "$manipulators" \
  '{description: $description, manipulators: $manipulators}')

# Profile 0 is "Default profile"; the only other one, "none", exists to turn
# everything off. Keys are sorted and indented to match how Karabiner itself
# rewrites this file, so its edits do not show up as whole-file diffs.
updated=$(jq --sort-keys --indent 4 --argjson rule "$rule" '
  .profiles[0].complex_modifications.rules |=
    (map(select(.description != $rule.description)) + [$rule])
' "$config")

if [ "${1:-}" = "--check" ]; then
  if printf '%s\n' "$updated" | cmp -s - "$config"; then
    exit 0
  fi
  echo "macOS/karabiner.json is stale; run macOS/yabai/gen-karabiner-rules.sh" >&2
  exit 1
fi

printf '%s\n' "$updated" > "$config"
echo "wrote $(printf '%s' "$manipulators" | jq length) hotkeys to $config"
