# use macvim instead of vim
brew 'macvim', args: ['with-override-system-vim', 'with-cscope', 'with-lua', 'with-luajit', 'python3']

# plugin requirments
brew 'cmake' # YouCompleteMe
brew 'go'
brew 'mono'
brew 'rust'
brew 'editorconfig' # editorconfig
brew 'pandoc' # vim-pandoc
