#!/usr/bin/env bash
# Bash Strict Mode: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'
# Bash Strict Mode

# linking files
dotfiles::symlink_files ~/.dotfiles/vim ~/.vim
dotfiles::symlink_files ~/.vim/vimrc ~/.vimrc
dotfiles::symlink_files ~/.vim ~/.config/nvim
mkdir ~/.local/vim

#Neovim
pip3 install neovim

# install plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

#Install Plugins
update_vim_plugins

