#!/bin/bash

# linking files
dotfiles::symlink_files ~/.dotfiles/vim ~/.vim
dotfiles::symlink_files ~/.vim/vimrc ~/.vimrc
dotfiles::symlink_files ~/.vim ~/.config/nvim
mkdir ~/.local/vim

# install plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

#Neovim
pip2 install neovim
pip3 install neovim
