#!/usr/bin/env bash
# Bash Strict Mode: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'
# Bash Strict Mode

# linking files
dotfiles::symlink_files ~/.dotfiles/vim ~/.vim
dotfiles::symlink_files ~/.vim/vimrc ~/.vimrc
dotfiles::symlink_files ~/.vim ~/.config/nvim
mkdir ~/.local/vim &> /dev/null || true

#Neovim
pip -q --disable-pip-version-check --no-python-version-warning install neovim

# install plug
if [[ ! -f ~/.vim/autoload/plug.vim ]] ; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

#Install Plugins
update_vim_plugins

