" Use Vim settings, rather then Vi
" This must be first, because it changes other options as a side effect.
set nocompatible

" Set leader and local leader
let mapleader=";"
let maplocalleader = "\\"

" ==== Load before vimrc file ====
if filereadable(expand("~/local/vim/vimrc.before"))
    source ~/local/vim/vimrc.before
endif

" ==== Plugin Initialization ====
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif
call plug#begin('~/.vim/bundle')
exe 'source' '~/.vim/plugins.vim'
call plug#end()

" ==== Custom Settings ====
let vimsettings = '~/.vim/settings'
for fpath in split(globpath(vimsettings, '*.vim'), '\n')
    exe 'source' fpath
endfor

" ==== Load after.vimrc file ====
" This files only loads other .vimrc files
" This is intended to allow overriding <Leader>.
if filereadable(expand("~/.local/vim/vimrc.after"))
    source ~/.local/vim/vimrc.after
endif
