#!/usr/bin/env bash
# Bash Strict Mode: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'
# Bash Strict Mode

source ~/.dotfiles/bash_utils.sh

if ! is_darwin ; then
    # only run on macOS
    return
fi

brew_infocmp=""
if [[ -f $HOMEBREW_PREFIX/opt/ncurses/bin/infocmp ]]; then
    brew_infocmp=$HOMEBREW_PREFIX/opt/ncurses/bin/infocmp
fi
if [[ $brew_infocmp == "" ]]; then
    echo_red "-[ ] run again once brew ncurses is installed"
    return
fi


if if_command_failed "/usr/bin/infocmp -x tmux-256color"; then
    # ref: https://gpanders.com/blog/the-definitive-guide-to-using-tmux-256color-on-macos/
    /bin/rm tmux-256color.src &> /dev/null || true
    $brew_infocmp -x tmux-256color \
        | sed -e 's/pairs#65536/pairs#32767/g' \
        | sed -e 's/pairs#0x10000/pairs#32767/g' \
        > tmux-256color.src
    /usr/bin/tic -x -o $HOME/.local/share/terminfo tmux-256color.src
    /bin/rm tmux-256color.src
fi

# test italics
# echo `tput sitm`italics`tput ritm` `tput smso`standout`tput rmso`

# test 256color
# for i in {0..255} ; do
#     printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
#     if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
#         printf "\n";
#     fi
# done
