#!/usr/bin/env bash
# Bash Strict Mode: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'
# Bash Strict Mode

source ~/.dotfiles/bash_utils.sh

if ! is_darwin ; then
    echo_yellow "-[ ] install missing packages. Find packages using:"
    cat <<EOF
        for Brewfile in {./Brewfile,./*/Brewfile} ; do
            full_brewfile="\$full_brewfile\\n\$( cat \$Brewfile  )"
        done
        echo \$full_brewfile | sort
EOF
    return
fi
if ! command_exists brew ; then
    echo_red "Error: homebrew is a prerequisite for this script. Install from brew.sh"
    exit 1
fi

# Install Brew programs
echo_yellow "-[ ] run \`update_brew\`"

# add brew's zsh and bash to the "acceptable shells" file
bash_count=$(cat /etc/shells | grep -c "$(brew --prefix)/bin/bash")
if [[ $bash_count < 1 ]] ; then
    echo "$(brew --prefix)/bin/bash" | sudo tee -a /etc/shells &> /dev/null
fi
zsh_count=$(cat /etc/shells | grep -c "$(brew --prefix)/bin/zsh")
if [[ $zsh_count < 1 ]] ; then
    echo "$(brew --prefix)/bin/zsh" | sudo tee -a /etc/shells &> /dev/null
fi

echo_yellow "-[ ] install dropbox"

# Xcode
# full xcode installation is required
xcodebuild -version &> /dev/null
if [[ $? != 0 ]] ; then
    echo_yellow "-[ ] TODO you need to install xcode from the app store"
fi
# so is xcode command line tools
xcode-select -version &> /dev/null
if [[ $? != 0 ]] ; then
    xcode-select --install
    sudo xcodebuild -license accept
fi
