#!/usr/bin/env bash
# Bash Strict Mode: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'
# Bash Strict Mode

dotfiles::symlink_files ~/.dotfiles/kmonad/start-keyboard.sh ~/.local/bin/start-keyboard
dotfiles::symlink_files ~/.dotfiles/kmonad/kill-keyboard.sh ~/.local/bin/kill-keyboard

dotfiles::symlink_files sudo ~/.dotfiles/kmonad/start-keyboard.sh /etc/profile.d/start-keyboard.sh

# sudo apt install evtest # for testing input devices
