#!/usr/bin/env bash
# Bash Strict Mode: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'
# Bash Strict Mode

dotfiles::symlink_files ~/.dotfiles/python/condarc ~/.condarc

mkdir $HOME/.local/python &> /dev/null || true
python3 -m venv ~/.local/python/user_env
source ~/.local/python/user_env/bin/activate

