#!/usr/bin/env bash
# Bash Strict Mode: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'
# Bash Strict Mode

dotfiles::symlink_files ~/.dotfiles/regolith3 ~/.config/regolith3

# sudo apt install regolith-desktop regolith-look-lascaille regolith-session-flashback brightnessctl

# sudo apt remove i3rocks-cpu-usage i3rocks-net-traffic i3rocks-time

