#!/usr/bin/env bash
# Bash Strict Mode: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'
# Bash Strict Mode

dotfiles::symlink_files $HOME/.dotfiles/tmux/tmux.conf $HOME/.tmux.conf;

mkdir -p ~/.local/tmux &> /dev/null || true
touch ~/.local/tmux/tmux.conf

# sudo apt install tmux
