source_if_found_else () {
    local file_source = $1
    local alternate_source = $2

    if [[ -s $file_source ]]; then
        source $file_source
    else
        source $alternate_source
    fi
}


# zshrc before
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.before" ]]; then
    source "${ZDOTDIR:-$HOME}/.zshrc.before"
else
    source "$HOME/.zsh/zshrc.before"
fi

# Source Prezto's zshrc
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc"
fi

for config_file ($HOME/.zsh/settings/*.zshrc) source $config_file

# zshrc after
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.after" ]]; then
    source "${ZDOTDIR:-$HOME}/.zshrc.after"
else
    source "$HOME/.zsh/zshrc.after"
fi

