# zshrc before
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.before" ]]; then
    source "${ZDOTDIR:-$HOME}/.zshrc.before"
else
    source "$HOME/.zsh/zshrc.before"
fi

# Source Prezto's zshrc
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc"
else
  echo "Prezto is not installed"
fi

# Source Config Files from .zsh/settings/*
for config_file ($HOME/.zsh/settings/*.zshrc) source $config_file

# Source all *.zshrc files in .local
for config_file ($HOME/.local/**/*.zshrc) source $config_file

# zshrc after
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.after" ]]; then
    source "${ZDOTDIR:-$HOME}/.zshrc.after"
else
    source "$HOME/.zsh/zshrc.after"
fi

