#!/usr/bin/env bash
# Bash Strict Mode: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'
# Bash Strict Mode

if ! is_linux ; then
    return
fi

# make trash file
mkdir ~/.Trash &> /dev/null || true

dotfiles::symlink_files ~/.dotfiles/linux/bin/pbcopy ~/.local/bin/pbcopy
dotfiles::symlink_files ~/.dotfiles/linux/bin/pbpaste ~/.local/bin/pbpaste
dotfiles::symlink_files ~/.dotfiles/linux/bin/read-selected-text ~/.local/bin/read-selected-text
dotfiles::symlink_files ~/.dotfiles/linux/bin/update_ubuntu ~/.local/bin/update_ubuntu

dotfiles::symlink_files ~/.dotfiles/linux/albert.conf ~/.config/albert.conf

source ./autokey/install

source ./settings.sh

echo "Installing packages"
update_ubuntu
